spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
